const express = require('express')
const routs = express.Router()
const passport = require('passport')
const admin = require('../model/admin_model')
const user = require('../model/user_model')
const indexController = require('../Controller/indexController')
routs.post('/session',passport.authenticate('local',{failureRedirect :'/login'}),indexController.dashboardSession)
routs.get('/',indexController.homePage)
routs.get('/admin_panel',passport.checkAuthentication,indexController.dashboard)
routs.get('/register',indexController.register)
routs.post('/registration',indexController.registration)
routs.get('/login',indexController.login)
routs.get('/forgotpassword',indexController.forgotpassword)
routs.post('/checkemail',indexController.checkemail)
routs.get('/checkotp',indexController.checkotp)
routs.post('/checkOtp',indexController.checkOtp)
routs.get('/newpassword',indexController.newpassword)
routs.post('/lostpassword',indexController.lostpassword)
routs.get('/changepassword',passport.checkAuthentication,indexController.changepassword)
routs.post('/editpassword',passport.checkAuthentication,indexController.editpassword)
routs.get('/profile',passport.checkAuthentication,indexController.profile)
routs.get('/updateProfile/:id',passport.checkAuthentication,indexController.updateprofile)
routs.post('/editprofile',admin.uploded_avatar,passport.checkAuthentication,indexController.editprofile)
routs.get('/movie_detail/:id',indexController.movie_detail)
routs.get('/book_now/:id',indexController.book_now)
routs.get('/bookShow/:id',indexController.book_show)
routs.post('/bookSheets',indexController.book_sheets)
routs.get('/ticket',indexController.ticket)
routs.get('/viewUser',indexController.viewUser)
routs.get('/deleteUser/:id',indexController.deleteUser)
routs.get('/sendMail',indexController.sendMail)
routs.get('/logout',(req,res)=>{   
     req.logout((err)=>{
          if(err){
               console.log(err);
          }
          res.redirect('/login')
     })
})
module.exports = routs